[package]
name = "merkle_tree_checksum"
description = "Computes a Merkle Tree hash over the given files"
version = "0.3.0"
authors = ["rlee287 <rlee287@yahoo.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#clap = "~2.33.3"
walkdir = "2.3.1"
chrono = "0.4.19"
indicatif = "0.15.0"
enquote = "1.0.3"
semver = "0.11.0"

#crc32-digest uses an outdated version of the Digest trait
digest = "0.9"
generic-array = "0.14.4"
crc32fast = "1.2.1"
sha2 = "0.9.2"
merkle_tree = { version = "~0.2.0", path = "../merkle_tree"}

[dependencies.clap]
version = "~2.33.3" # ~ specification from crates.io
default-features = false
features = [ "wrap_help", "color" ]

# Pull in perf feature to speed up matching
# Currently transitive dependency of indicatif, but may help with parsing later
[dependencies.regex]
version = "1.5.4"
default-features = false
features = ["std", "perf"]

# Hashing is the bottleneck from profiling
# We don't care about dependency internals when debugging our code
[profile.dev.package.sha2]
opt-level = 3
[profile.dev.package.crc32fast]
opt-level = 3

[profile.release]
debug = true
