[package]
name = "merkle-tree"
version = "0.1.0"
authors = ["rlee287 <rlee287@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
digest = "0.9"
generic-array = "0.14.4"
# hmac = "0.10.1"
