[package]
name = "merkle_tree"
version = "0.4.1"
authors = ["rlee287 <rlee287@yahoo.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
digest = "0.10"
generic-array = "0.14"
num-iter = "0.1"
# The more popular "generator" library has potential unsoundness issues
# Prefering genawaiter with more documentation and no stack-switch shenanigans
genawaiter = {version = "0.99", default-features = false}
async-recursion = "1.0"

crossbeam-channel = "0.5"
[dependencies.oneshot]
version = "0.1"
default-features = false
features = ["std"]

[dev-dependencies]
sha2 = "0.10"
permutohedron = "0.2"
