[package]
name = "merkle_tree_test_utils"
version = "0.1.0"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
merkle_tree = { version = "=0.4.0", path = "../merkle_tree"}